<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<section class="page-bar">
    <div class="actions">
        <?php echo $this->getChildHtml('store_language') ?>
        <?php echo $this->getChildHtml('currency_switcher') ?>
        <?php echo $this->getChildHtml('topSearch') ?>
    </div><!-- .actions -->
</section>

<header id="header" class="page-header">
    <div class="container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <?php if($this->getLogoSrc()): ?>
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            <?php else: ?>
                <?php echo $this->getLogoAlt() ?>
            <?php endif; ?>
        </a>

        <?php /*
        <div class="skip-links">
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>

            <a href="#header-search" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>

            <a href="#header-account" class="skip-link skip-account">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Account'); ?></span>
            </a>

            <div class="header-minicart">
                <?php echo $this->getChildHtml('minicart_head'); ?>
            </div>
        </div>

        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>

        <div id="header-cart" class="skip-content">
            <div class="mini-cart">
                <div class="menu-wrapper">
                    <div class="menu cart-menu">
                        <div class="empty">Your cart is empty.</div>
                    </div>
                </div>
            </div>
        </div>
        */ ?>
    </div><!-- .container -->
</header>

<?php echo $this->getChildHtml('topContainer'); ?>