<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <?php if($this->getUseContainer()): ?>
        <div class="pager pager-no-toolbar">
    <?php endif ?>

    <?php if($this->getShowAmounts() || $this->getShowPerPage()): ?>
        <?php if($this->getShowAmounts()): ?>
            <?php if($this->getLastPageNum()>1): ?>
                <div class="amount amount--has-pages">
                    <p><?php echo $this->__('%s-%s of %s Items', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?></p>
                </div>
            <?php else: ?>
                <div class="amount amount--no-pages">
                    <p><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></p>
                </div>
            <?php endif; ?>
        <?php endif ?>

        <?php if($this->getShowPerPage()): ?>
            <div class="limiter">
                <label><?php echo $this->__('View') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Results per page'); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div><!-- .limiter -->
        <?php endif ?>
    <?php endif; ?>

    <?php if($this->getLastPageNum() > 1): ?>
        <div class="pages">
            <ol class="pagination">
            <?php if (!$this->isFirstPage()): ?>
                <li>
                    <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                        <?php if(!$this->getAnchorTextForPrevious()): ?>
                            <?php echo $this->__('&laquo;') ?>
                        <?php else: ?>
                            <?php echo $this->getAnchorTextForPrevious() ?>
                        <?php endif;?>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($this->canShowFirst()): ?>
                <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif;?>

            <?php if ($this->canShowPreviousJump()): ?>
                <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
            <?php endif;?>

            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                    <li class="current"><span><?php echo $_page ?></span></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($this->canShowNextJump()): ?>
                <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
            <?php endif;?>

            <?php if ($this->canShowLast()): ?>
                <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
            <?php endif;?>

            <?php if (!$this->isLastPage()): ?>
                <li>
                    <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                        <?php if(!$this->getAnchorTextForNext()): ?>
                            <?php echo $this->__('&raquo;') ?>
                        <?php else: ?>
                            <?php echo $this->getAnchorTextForNext() ?>
                        <?php endif;?>
                    </a>
                </li>
            <?php endif;?>
            </ol>
        </div><!-- .pages -->
    <?php endif; ?>

    <?php if($this->getUseContainer()): ?>
        </div><!-- .pager pager-no-toolbar -->
    <?php endif ?>
<?php endif ?>