<div class="footer-container">
    <footer>
        <address><?php echo $this->getCopyright() ?></address>
    </footer>
</div>

<!--[if lt IE 7 ]>
    <script src="<?php echo $this->getSkinUrl('js/dd_belatedpng.js') ?>"></script>
    <script> DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images </script>
<![endif]-->
  
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6. chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
<![endif]-->