<div class="account-dashboard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('sales'); ?>
    <?php echo $this->getChildHtml('wishlist'); ?>

    <?php //echo $this->getChildHtml('top') ?>
    <?php /* Extensions placeholder */ ?>
    <?php //echo $this->getChildHtml('customer.account.dashboard.extra') ?>
    <?php //echo $this->getChildHtml('info') ?>
    <?php //echo $this->getChildHtml('address') ?>
    <?php //echo $this->getChildHtml('info1') ?>
    <?php //echo $this->getChildHtml('info2') ?>
</div><!-- .account-dashboard -->