<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>

        <?php if($this->getMode()!='grid'): // list mode ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                                    one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                                    we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                                    will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                                    This $_imgSize value could even be decreased further, based on the page layout
                                    (one column, two column, three column) and number of product columns. */ ?>
                            <?php $_imgSize = 300; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                    <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>

                                    <?php
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach($_nameAfterChildren as $_nameAfterChildName):
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                    ?>
                                        <?php echo $_nameAfterChild->toHtml(); ?>
                                    <?php endforeach; ?>
                                </div>
                                <div class="product-secondary">
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                </div>
                                <div class="product-secondary">
                                    <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                        <p class="action"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                    <?php elseif($_product->isSaleable()): ?>
                                        <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                                    <?php else: ?>
                                        <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                        <?php endif; ?>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol><!-- .products-list -->
        <?php else: // grid mode ?>
            <div class="row products-grid">
                <?php foreach ($_productCollection as $_product): ?>
                    <div class="column product-item">
                        <div class="product-item-image">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(388, 480); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>

                            <div class="product-item-overlay">
                                <a class="link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"></a>

                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>">
                                        <?php echo $this->__('Add to Wishlist') ?>
                                    </a>
                                <?php endif; ?>

                                <?php if($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>">
                                        <?php echo $this->__('Add to Compare') ?>
                                    </a>
                                <?php endif; ?>

                                <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                    <a class="button" href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to Cart') ?>">
                                        <?php echo $this->__('Add to Cart') ?>
                                    </a>
                                <?php elseif(!$_product->isSaleable()): ?>
                                    <span class="button"><?php echo $this->__('Out of stock') ?></span>
                                <?php endif; ?>
                            </div><!-- .product-item-overlay -->
                        </div><!-- .product-image -->

                        <div class="product-item-info">
                            <h2 class="product-item-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h2><!-- .product-item-name -->

                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div><!-- .product-item-info -->
                    </div><!-- .column -->
                <?php endforeach ?>
            </div><!-- .row -->
        <?php endif; ?>

        <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar-bottom.phtml')->toHtml(); ?>
    </div><!-- .category-products -->
<?php endif; ?>