<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="container account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <div class="account-login-contents">
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <?php echo $this->getBlockHtml('formkey'); ?>

            <div class="row<?php if ($this->helper('customer')->isRegistrationAllowed()): ?> registration-open<?php endif; ?>">
                <div class="column column-left">
                    <div class="column-inner">
                        <h2><?php echo $this->__('Existing Customers') ?></h2>
                        <p class="form-instructions"><?php echo $this->__('Please log in if you are already registered and have an account.') ?></p>

                        <ul class="form-list">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>

                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                        <div class="buttons-set">
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>

                            <button type="submit" class="button" title="<?php echo $this->__('Log In Securely') ?>" name="send" id="send2">
                                <?php echo $this->__('Log In Securely') ?>
                            </button>
                        </div>
                    </div><!-- .column-inner -->
                </div><!-- .column -->

                <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                    <div class="column column-right">
                        <div class="column-inner">
                            <h2><?php echo $this->__('New Customers') ?></h2>
                            <p class="form-instructions"><?php echo $this->__('New here? Let\'s be friends. Make it official and create an account today.') ?></p>

                            <div class="buttons-set">
                                <a title="<?php echo $this->__('Create an Account') ?>" class="button" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>">
                                    <?php echo $this->__('Create an Account') ?>
                                </a>
                            </div>
                        </div><!-- .column-inner -->
                    </div><!-- .column -->
                <?php endif; ?>
            </div><!-- .row -->

            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
    </div><!-- .account-login-contents -->

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div><!-- .container -->