<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <?php if($this->getLastPageNum() > 1): ?>
        <div class="amount amount--has-pages">
            <p><?php echo $this->__('%s-%s of %s Items', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?></p>
        </div>
    <?php else: ?>
        <div class="amount amount--no-pages">
            <p><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></p>
        </div>
    <?php endif; ?>

    <?php if( $this->isExpanded() ): ?>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
            <?php $_modes = $this->getModes(); ?>

            <?php if($_modes && count($_modes) > 1): ?>
                <div class="view-mode">
                    <label><?php echo $this->__('View as') ?></label>
                    <?php foreach ($this->getModes() as $_code=>$_label): ?>
                        <?php if($this->isModeActive($_code)): ?>
                            <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
                        <?php else: ?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div><!-- .view-mode -->
            <?php endif; ?>
        <?php endif; ?>

        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>

            <div class="style-select">
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Sort By') ?>">
                    <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                        <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                            <?php echo $this->__($_order) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div><!-- .style-select -->
        </div><!-- .sort-by -->
    <?php endif; ?>

    <div class="limiter">
        <label><?php echo $this->__('View') ?></label>

            <select onchange="setLocation(this.value)" title="<?php echo $this->__('Results per page'); ?>">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select>

    </div><!-- .limiter -->
</div><!-- .toolbar -->
<?php endif ?>
