<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="<?php echo $this->getLang(); ?>"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="<?php echo $this->getLang(); ?>"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="<?php echo $this->getLang(); ?>"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?php echo $this->getLang(); ?>"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head'); ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<?php echo $this->getChildHtml('after_body_start'); ?>
    <?php echo $this->getChildHtml('global_notices'); ?>
    
    <div class="page">
        <?php echo $this->getChildHtml('header'); ?>
        <div class="main-container col2-right-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs'); ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages'); ?>
                    <?php echo $this->getChildHtml('content'); ?>
                </div><!-- .col-main -->
                
                <div class="col-right sidebar">
                	<?php echo $this->getChildHtml('right'); ?>
                </div><!-- .col-right sidebar -->
            </div><!-- .main -->
        </div><!-- .main-container col2-right-layout -->
    </div><!-- .page -->

	<?php echo $this->getChildHtml('footer'); ?>
    <?php echo $this->getChildHtml('before_body_end'); ?>
    <?php echo $this->getChildHtml('site.bottom.css.js'); ?>
	<?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
