<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->   
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head'); ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<?php echo $this->getChildHtml('after_body_start'); ?>
	<?php echo $this->getChildHtml('global_notices'); ?>	

	<div class="wrapper">     
	    <div class="page">
	        <?php echo $this->getChildHtml('header'); ?>
	        
	        <div class="main-container col2-right-layout">
	            <div class="main">
	                <?php echo $this->getChildHtml('breadcrumbs'); ?>
	                <div class="col-main">
	                    <?php echo $this->getChildHtml('global_messages'); ?>
	                    <?php echo $this->getChildHtml('content'); ?>
	                </div><!-- .col-main -->
	                
	                <div class="col-right sidebar">
	                	<?php echo $this->getChildHtml('right'); ?>
	                </div><!-- .col-right sidebar -->
	            </div><!-- .main -->
	        </div><!-- .main-container col2-right-layout -->
	        
			<?php echo $this->getChildHtml('footer'); ?>
	    </div><!-- .page -->
	</div><!-- #wrapper -->
	
    <?php echo $this->getChildHtml('before_body_end'); ?>
    <?php echo $this->getChildHtml('site.bottom.css.js'); ?>
	<?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
