<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div class="product-img-box">
    <div class="product-image">
        <div class="owl-carousel owl-theme">
            <?php if ($_product->getImage() == 'no_selection'): ?>
                <div class="item">
                    <img
                        class="gallery-image visible js-gallery-image-no-selection"
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
                        alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
                        title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
                </div>
            <?php endif; ?>

            <?php
                if ($_product->getImage() == 'no_selection'){
                    $i = 1;
                } else {
                    $i = 0;
                }
            ?>

            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php
                    $_imageUrl = $this->helper('catalog/image')
                                      ->init($_product, 'image', $_image->getFile())
                                      ->keepFrame(false)
                                      ->constrainOnly(true)
                                      ->resize(1200);

                    $_imageUrlZoom = $this->helper('catalog/image')
                                      ->init($_product, 'image', $_image->getFile())
                                      ->keepFrame(false)
                                      ->constrainOnly(true)
                                      ->resize(1560);
                ?>

                <div class="item">
                    <img
                        id="image-<?php echo $i; ?>"
                        class="gallery-image<?php if($i == 0): ?> visible<?php endif; ?>"
                        src="<?php echo $_imageUrl; ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
                        data-zoom-image="<?php echo $_imageUrlZoom; ?>"
                        alt="<?php echo $this->escapeHtml($this->getImageLabel()); ?>"
                        title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
                </div>
            <?php $i++; endforeach; ?>
        </div><!-- .owl-carousel -->
    </div><!-- .product-image -->

    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <div class="owl-carousel owl-theme">
                <?php
                    if ($_product->getImage() == 'no_selection'){
                        $i = 1;
                    } else {
                        $i = 0;
                    }
                ?>

                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <?php
                    if (($filterClass = $this->getGalleryFilterHelper()) && ($filterMethod = $this->getGalleryFilterMethod()) && !Mage::helper($filterClass)->$filterMethod($_product, $_image)):
                        continue;
                    endif;
                    ?>
                    <div class="item<?php if($i == 0): ?> visible<?php endif; ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(160, 130); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </div>
                <?php $i++; endforeach; ?>
            </div><!-- .owl-carousel -->
        </div>
    <?php endif; ?>

    <?php echo $this->getChildHtml('after'); ?>
</div><!-- .product-img-box -->