<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div class="product-img-box">
    <div class="product-image">
        <div class="owl-carousel owl-theme">
            <?php if ($_product->getImage() == 'no_selection'): ?>
                <div class="item">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>" title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
                </div>
            <?php endif; ?>

            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php
                    $_imageUrl = $this->helper('catalog/image')
                                      ->init($_product, 'image', $_image->getFile())
                                      ->keepFrame(false)
                                      ->constrainOnly(true)
                                      ->resize(1200);
                ?>

                <div class="item">
                    <img src="<?php echo $_imageUrl; ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>" title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
                </div>
            <?php endforeach; ?>
        </div><!-- .owl-carousel -->
    </div><!-- .product-image -->

    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <div class="owl-carousel owl-theme">
            <?php $i = 0; foreach ($this->getGalleryImages() as $_image): ?>
                <?php
                if (($filterClass = $this->getGalleryFilterHelper()) && ($filterMethod = $this->getGalleryFilterMethod()) && !Mage::helper($filterClass)->$filterMethod($_product, $_image)):
                    continue;
                endif;
                ?>
                <div class="item" data-image-index="<?php echo $i; ?>">
                    <a href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </a>
                </div>
            <?php $i++; endforeach; ?>
            </div><!-- .owl-carousel -->
        </div>
    <?php endif; ?>

    <?php echo $this->getChildHtml('after'); ?>
</div><!-- .product-img-box -->